name: socialbennett
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  flutter_svg:  # help us to use SVG in our app
  provider: ^4.3.1 # for State management
  lottie:
  firebase_core: ^1.0.4
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker: ^0.7.4
  slide_popup_dialog: ^0.0.2
  pinput: ^1.2.0
  carousel_slider: ^2.3.1
  dots_indicator: ^1.2.0
  shared_preferences: ^2.0.5
  animated_splash_screen: ^1.1.0
  flutter_easyloading: ^3.0.0
  direct_select_flutter: ^1.1.1
  search_choices: ^2.0.6
  flutter_swipe_button: ^1.1.0
  skeletons: ^0.0.3
  fluttertoast: ^7.1.1
  paytm: ^3.0.0
  http: ^0.13.3
  getwidget: ^2.0.3
  geocoding: ^2.0.0
  geolocator: ^7.4.0
  syncfusion_flutter_gauges: ^19.2.55
  flutter_awesome_alert_box: ^2.1.0
  menu_button: ^1.4.2+1
  paginate_firestore:
  cached_network_image: ^3.1.0
  loading_skeleton: 1.0.2
  algolia: ^1.0.1
  rounded_loading_button: ^2.0.3
  cool_alert: ^1.1.0
  pdf: ^3.4.2
  url_launcher: any
  open_file:
  intl:
  barcode_widget:
  twilio_flutter: ^0.0.9
  path_provider: ^2.0.1
  package_info_plus: ^1.0.6
  card_swiper : ^1.0.4
  flutter_staggered_grid_view: ^0.4.0
  flip_card: ^0.5.0
  font_awesome_flutter: ^9.1.0
#  bordered_text: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: OpenSans
      fonts:
        - asset: assets/fonts/opensans/OpenSans-Regular.ttf

    - family: Playlist
      fonts:
        - asset: assets/fonts/playlist/PlaylistScript.ttf
#              - asset: assets/fonts/playlist/Muli-Bold.ttf
#                weight: 700
#              - asset: assets/fonts/playlist/Muli-Light.ttf
#                weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
